### ISSUE TITLE
Conflict with tinker`s compendium (tinker´s defense)

### ISSUE THREAD

**Issue by NeroAzure** [Shnupbups/TinkersAether#10]
When having both mods, yours and tinkers compendium installed, there is a conflict with the `rooted` trait as both try to register it, unfortunately i dont know on which side the check for the trait is missing, a small suggestion where to rename it to `heavenly rooted` or somthing in this manner, if the traits aren´t really the same (i cant tell, since i start mc with your mod right now for the first time).
As for now i had to disable the skyroot material to make them compatible.

**Comment by Shnupbups** [comment]
Noted! A version will be released renaming the 'Rooted' trait to 'Skyrooted'.

**Comment by Shnupbups** [comment]
Fixed in 1.2.0
