### ISSUE TITLE
Solution to not adding Valerkye metals to Aether Legacy Chests

### ISSUE THREAD

**Issue by AlexModGuy** [Shnupbups/TinkersAether#13]
https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/event/EventLiving.java#L520

I saw that you had issues adding your own Valerkye metal to the default Aether chests. This code should help provide a solution to your problem.

**Comment by Shnupbups** [comment]
I assume you meant to link to this line?
https://github.com/Alex-the-666/Ice_and_Fire/blob/5b87e4277521ba87ec3bf39e6baca5e9e48f1e7c/src/main/java/com/github/alexthe666/iceandfire/event/EventLiving.java#L565

The problem I have with adding the ingots to the chests cannot be solved with this method, as the Aether Legacy dungeon chests do not currently use the LootTables system, but rather have their loot generation hardcoded.

The Aether Legacy devs have plans to migrate to the LootTables system, however, and once they do my job will be simple.

But as it stands right now, it is simply not possible to use this method to add loot to the chests.

(If you did however intend to link to the line you *did* link to, I would really rather not fire an event every single time a chest is opened, figure out how to check if said chest is a silver dungeon chest, figure out if it's being opened for the first time, then add loot to it. That's... a bit silly.)
