### ISSUE TITLE
tinkers eather crash on start up

### ISSUE THREAD

**Issue by deadlywolf301** [Shnupbups/TinkersAether#19]
it crashes due to a creative tab issue according to crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/30/20 4:38 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinker's Aether (tinkersaether)
Caused by: java.lang.NoClassDefFoundError: com/legacy/aether/registry/creative_tabs/AetherCreativeTabs$AetherTab
	at shnupbups.tinkersaether.modules.ModuleBase.<clinit>(ModuleBase.java:69)
	at shnupbups.tinkersaether.TinkersAether.preInit(TinkersAether.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.legacy.aether.registry.creative_tabs.AetherCreativeTabs$AetherTab
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 907953360 bytes (865 MB) / 2653945856 bytes (2531 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 123 mods loaded, 123 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                                | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                         | None                                     |
	| LCH   | mcp                               | 9.42                     | minecraft.jar                                         | None                                     |
	| LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | buildcraftlib                     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftcore                    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcrafttransport               | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | additionalpipes                   | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                           | None                                     |
	| LCH   | aeadditions                       | 1.2                      | aeadditions-1.12.2-1.2.jar                            | None                                     |
	| LCH   | aether_legacy                     | 1.5.1                    | aether-1.12.2-v1.5.1.jar                              | None                                     |
	| LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCH   | flyringbaublemod                  | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar           | None                                     |
	| LCH   | aoa3                              | 3.3.5                    | AoA3-3.3.5.jar                                        | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCH   | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.586.jar                     | None                                     |
	| LCH   | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                       | None                                     |
	| LCH   | modtweaker                        | 4.0.18                   | modtweaker-4.0.18.jar                                 | None                                     |
	| LCH   | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LCH   | base                              | 3.13.0                   | base-1.12.2-3.13.0.jar                                | None                                     |
	| LCH   | basicmetals                       | 0.0.1                    | basicmetals-1.12-1.0.jar                              | None                                     |
	| LCH   | betterbedrock                     | 5.1                      | BetterBedrock-1.12.2-5.1.11.jar                       | None                                     |
	| LCH   | bettercombatmod                   | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                         | None                                     |
	| LCH   | blockdrops                        | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                           | None                                     |
	| LCH   | bountifulbaubles                  | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar                    | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftcompat                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCH   | buildinggadgets                   | 2.8.4                    | BuildingGadgets-2.8.4.jar                             | None                                     |
	| LCH   | ccm                               | 1.0                      | ccm-1.0.jar                                           | None                                     |
	| LCH   | claybucket                        | 1.1                      | ClayBucket-1.12-1.1.jar                               | None                                     |
	| LCH   | clayconversion                    | 1.4                      | clayconversion-1.12.x-1.4.jar                         | None                                     |
	| LCH   | clayworldgen                      | 1.1.0-1.12               | ClayWorldGen-1.1.0-1.12.0.jar                         | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                           | None                                     |
	| LCH   | enderio                           | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderiointegrationtic             | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LCH   | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| LCH   | twilightforest                    | 3.11.1020                | twilightforest-1.12.2-3.11.1020-universal[1].jar      | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LCH   | contenttweaker                    | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                       | None                                     |
	| LCH   | conarm                            | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                             | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | controlling                       | 3.0.10                   | Controlling-3.0.10.jar                                | None                                     |
	| LCH   | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.586.jar                     | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.586.jar                     | None                                     |
	| LCH   | curio                             | 1.0.4                    | Curio-1.0.4.jar                                       | None                                     |
	| LCH   | cxlibrary                         | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                            | None                                     |
	| LCH   | durability101                     | 0.0.3                    | Durability101-1.12-0.0.3.jar                          | None                                     |
	| LCH   | enderore                          | 1.12.2-v1.1              | Ender Ore-1.12.2-v1.1.jar                             | None                                     |
	| LCH   | enderiobase                       | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderioconduits                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | refinedstorage                    | 1.6.16                   | refinedstorage-1.6.16.jar                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | enderioconduitsrefinedstorage     | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderiointegrationforestry        | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderiointegrationticlate         | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderiomachines                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderiopowertools                 | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                             | None                                     |
	| LCH   | enderioendergy                    | 5.2.59                   | EnderIO-endergy-1.12.2-5.2.59.jar                     | None                                     |
	| LCH   | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | shetiphiancore                    | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                       | None                                     |
	| LCH   | endertanks                        | 1.6.8                    | endertanks-1.12.0-1.6.8.jar                           | None                                     |
	| LCH   | erebus                            | 1.0.31                   | Erebus-1.0.31.jar                                     | None                                     |
	| LCH   | exp_ore                           | 1.12.2-1.0               | ExpOre-1.12.2-1.0.jar                                 | None                                     |
	| LCH   | moa_dlc                           | 1.2.1                    | extra-moas-1.12.2-1.2.1.jar                           | None                                     |
	| LCH   | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                           | None                                     |
	| LCH   | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                   | None                                     |
	| LCH   | fastflyblockbreaking              | MC1.9.4-MC1.12.2-1.1     | fastflyblockbreaking-MC1.9.4-MC1.12.2-1.1.jar         | None                                     |
	| LCH   | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                                 | None                                     |
	| LCH   | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                    | None                                     |
	| LCH   | goodnightsleep                    | 0.2.2                    | good-nights-sleep-1.12.2-v0.2.2.jar                   | None                                     |
	| LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | jeiintegration                    | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                       | None                                     |
	| LCH   | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	| LCH   | jeroreintegration                 | 1.1.0                    | JEROreIntegration-1.12.2-1.1.0.jar                    | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| LCH   | jrftl                             | 1.1                      | JRFTL[1.12.2]-1.1.jar                                 | None                                     |
	| LCH   | justenoughreactors                | 1.1.3.61                 | JustEnoughReactors-1.12.2-1.1.3.61.jar                | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
	| LCH   | lost_aether                       | 1.0.2                    | lost-aether-content-1.12.2-1.0.2.jar                  | None                                     |
	| LCH   | netherlessquartz                  | 1.1.0                    | ManPuppy's Netherless Quartz Mod-v1.1.0.jar           | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                         | None                                     |
	| LCH   | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar               | None                                     |
	| LCH   | moartinkers                       | 0.6.0                    | moartinkers-0.6.0.jar                                 | None                                     |
	| LCH   | morefurnaces                      | 1.10.6.12                | MoreFurnaces-Omnifactory-Edition-1.12.2-1.10.6.12.jar | None                                     |
	| LCH   | simplecore                        | 1.7.3.4                  | simplecore-1.12.2-1.7.3.4.jar                         | None                                     |
	| LCH   | netherrocks                       | 1.7.1.2                  | netherrocks-1.12.2-1.7.1.2.jar                        | None                                     |
	| LCH   | nevokacore                        | 1.0.2                    | nevoka-core-1.0.2.jar                                 | None                                     |
	| LCH   | samsocean                         | 1.0.2                    | OceanFloor-1.12.2-1.0.2.jar                           | None                                     |
	| LCH   | oreexcavation                     | 1.4.150                  | OreExcavation-1.4.150.jar                             | None                                     |
	| LCH   | patchouli                         | 1.0-21                   | Patchouli-1.0-21.jar                                  | None                                     |
	| LCH   | llibrary                          | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | rats                              | 3.2.14                   | rats-3.2.14-1.12.2.jar                                | None                                     |
	| LCH   | reborncore                        | 3.19.4.529               | RebornCore-1.12.2-3.19.4.529-universal.jar            | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | rebornstorage                     | 1.0.0                    | RebornStorage-1.12.2-3.3.4.1.jar                      | None                                     |
	| LCH   | rsinfinitewireless                | 1.2                      | rsinfinitewireless-1.2.jar                            | None                                     |
	| LCH   | siliconmod                        | 1.12.2-1.4               | siliconmod-1.12.2-1.4.jar                             | None                                     |
	| LCH   | simplesmelteryaccelerator         | 1.0.1                    | SimpleSmelteryAccelerator-1.0.1.jar                   | None                                     |
	| LCH   | simpletcon                        | 3.0                      | SimpleTcon-3.0b.jar                                   | None                                     |
	| LCH   | craftable_slimeball               | 1.0.0                    | SlimeBottles.jar                                      | None                                     |
	| LCH   | stg                               | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                  | None                                     |
	| LCH   | tardis                            | 0.1.4A                   | tardis-0.1.4A.jar                                     | None                                     |
	| LCH   | tesseract                         | 1.0.12                   | tesseract-1.0.12-mc1.12.jar                           | None                                     |
	| LCH   | theaurorian                       | 1.12.2-Release           | theaurorian-1.12.2-release-aug1020.jar                | None                                     |
	| LCH   | thutcore                          | 5.21.0                   | thutcore-1.12.2-5.21.0.jar                            | None                                     |
	| LCH   | thutcore_compat                   | 1.0                      | thutcore-1.12.2-5.21.0.jar                            | None                                     |
	| LCH   | thuttech                          | 6.1.6                    | thuttech-1.12.2-6.1.6.jar                             | None                                     |
	| LCH   | tinkeredhegemony                  | @VERSION@                | TinkeredHegemony-0.2.1.jar                            | None                                     |
	| LCH   | tinkersaddons                     | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                      | None                                     |
	| LCE   | tinkersaether                     | 1.3.0                    | tinkersaether-1.3.0.jar                               | None                                     |
	| LC    | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                    | None                                     |
	| LC    | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                   | None                                     |
	| LC    | xat                               | 0.30                     | Trinkets and Baubles-0.30.1.jar                       | None                                     |
	| LC    | uncrafted                         | 3.0.1                    | Uncrafted 1.12  (v.3.0.1).jar                         | None                                     |
	| LC    | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar                 | None                                     |
	| LC    | wanionlib                         | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                              | None                                     |
	| LC    | wearablebackpacks                 | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar                    | None                                     |
	| LC    | morerefinedstorage                | 1.1.9                    | morerefinedstorage-1.1.9.jar                          | d68758e79dc66e96a127d04bc039f1ec860a1537 |
	| LC    | superores                         | 1.9.0_1.12               | superores-1.9.0-1.12.jar                              | None                                     |
	| LC    | unidict                           | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6911' Renderer: 'Intel(R) UHD Graphics 620'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/kraig/Twitch/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.4.529
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by Mrthomas20121** [comment]
it's crashing because it need to be updated to work with the latest aether version.

**Comment by forresthopkinsa** [comment]
Fixed in #17, download jar from there until it's merged

**Comment by deadlywolf301** [comment]
thanks
