### ISSUE TITLE
Creative Tab Crash on Startup?

### ISSUE THREAD

**Issue by SylvanusPC** [Shnupbups/TinkersAether#20]
Hello all. I'm making a modpack for my friends and I and wanted to include Aether as well as Tinker's Aether, but I am having a problem. Whenever I start the pack, the game crashes almost immediately and presents me with this error message:

https://pastebin.com/t5MJX43e

I'm no expert but it looks like there's something wrong with the creative tab that the game sees as an irreconcilable error. Any help would be appreciated, thanks.

**Comment by seasonedfish** [comment]
I'm getting the same `NoClassDefFoundError`. Crash log: https://pastebin.com/XCavEVRj
