### ISSUE TITLE
issues with recent Valkyrie stuff

### ISSUE THREAD

**Issue by Darkmega18** [Shnupbups/TinkersAether#6]
The recipes which I presume are the meltdown recipes for the 4 armor pieces are "empty" recipes in my JEI. they do however still melt. 

As for the tools, the attack reach doesn't appear to be working unlike the valkyrie lance if that was meant to be a thing. but the block scanning and breaking reach does. For attack range, it'd also be awesome if the super bonk on the pan would work at range too, but if I had to guess that would just automatically hit far if the attack range actually improved.

**Comment by Shnupbups** [comment]
Attack reach has not been added yet due to difficulties in getting it to work, but I do plan on adding it once I figure it out.

As for the 'empty' recipes, I'll look into it.

**Comment by Shnupbups** [comment]
The pan's super bonk still doesn't have extended range, but everything else has been fixed/added in version 1.1.1.

**Comment by Darkmega18** [comment]
neat. So we've got Attack range like the originals? Neat! :D
